project:
  type: website

website:
  title: "Corwin Dark"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about me.qmd
      - Introduction.qmd
      - Data Sources.qmd
      - Data Visualization.qmd
      - Exploratory Data Analysis.qmd
      - ARMA ARIMA SARIMA Models.qmd
      - ARIMAX SARIMAX VAR.qmd
      - Spectral Analysis and Filtering.qmd
      - Financial Time Series Models (ARCH GARCH).qmd
      - Deep Learning for TS.qmd
      - Conclusions.qmd
      - dv.qmd

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true



