project:
  type: website

website:
  title: "Corwin Dark"
  navbar:
    left:
      - href: index.qmd
        text: About Me
      - Introduction.qmd
      - Data Sources.qmd
      - Data Visualization.qmd
      - Exploratory Data Analysis.qmd
      - ARMA ARIMA SARIMA Models.qmd
      - ARIMAX SARIMAX VAR.qmd
      - Financial Time Series Models (ARCH GARCH).qmd
      - Deep Learning for TS.qmd
      - Conclusions.qmd
      - dv.qmd

format:
  html:
    theme: sandstone
    toc: true
    css: styles.css
    code-fold: true
    code-summary: "Show Code"

execute:
  freeze: true 



