---
title: "Data Sources"
author: "Corwin Dark"
---


<h2> Planning Models </h2>

We have the following independent variables:
1. Interest Rate Expectation Changes - 3 Months 
2. Interest Rate Expectation Changes - 6 Months 
3. Interest Rate Expectation Changes - 1 Year
4. Extreme Weather Events - Daily Event Number
5. Extreme Weather Events - Daily Property Damage
6. Extreme Weather Events - Daily Casualties
7. Extreme Weather Events - Hurricanes
8. Expected Volatility (VIX) - Value
9. Expected Volatility (VIX) - Daily Change
10. Work Stoppages - Daily Striking Worker Total
11. Work Stoppages - Daily New Strike Beggining
12. Work Stoppages - Daily New Workers Striking

We will combine these 12 predictors into 5 models, for SPY, QQQ, and IWM intraday volatility:
1. (ARIMAX) SPY ~ Interest Rate 1-Year + Daily Weather Property Damage + Daily VIX Change + Daily Striking Worker Total
2. (VAR) SPY ~ Interest Rate 6-Months + Daily Weather Event Number + Daily VIX Value + Daily Striking Workers 
3. (ARIMAX) IWM ~ Daily New Strikes Beggining + Casualties + Hurricanes + Interest Rate 3-Months
4. (VAR/ARIMAX) QQQ ~ All Interest Rates + All Extreme Weather Events + Daily VIX Change + Daily Striking Workers
5. (ARIMAX) QQQ ~ Interest Rate 3 months + Daily Property Damage + Daily VIX Change + Daily New Striking Workers



<h2> Preparing Exogenous Data </h2>

First we need to create all 12 predictors, then we can combine them to estimate the models as needed.